language: android
android:
  components:
    - platform-tools
    - build-tools-26.0.2
    - android-27
    - extra-android-m2repository
addons:
  sonarcloud:
    organization: "markusfisch-github"
    token:
      secure: "vyS0pJmeqVGuRgMQcVQTSOkIyH+GBdL3gC1giSVl/6OaY6Ovx6dOxoqyzrsO8pkYO4jS1BjcdXkkwmMlpCRcQDQbFwXDSHWxpHmpZGZY2E3+xDHi3Z7r5psWBL4Y5RcD7YhOYN//ap0us2kzmGRq6C9pXmrq/Q/TejUpeh1Izk1630KTMpJqVRsmrCqNpoUk/ljmBKG8u1FPxf/Q0J2uzcfSG0eQghAuXSheKQvRLt3IRQQEaL5cjfasKFYd1eFc2uIyuApeCY6ya2JmcsgIXQPKBlKjFruqWQS1nscYQazRDgcMzTgPWLGpFlFNSaCD0QVljjOCGsoQeY74fel93E+Gs4D0U1uk+3bRLqmH+muSUqLI517b7OaWpUpOTNYkXChyQYyTlXfDXbHb+Pn1gkd4ZqAh8ZXtGqPbw75olw7qY83GwZC6bX/rwsthy7ICYy7Rj4nRfomwNnvio5enjUfIXTog+Z07RXJox3aFZfDSxKngTGy8+mCYu6pOs+ByTowQ0T9eeviCx70cE80b5OHyM3FMFjDR74LMbj37M8/6omNRypUcDsC03MmLi5OzTd3qPK2Xq35Q5Wv9+uFdc1OY57GYx8LjFJNQ3zi9i7fXea3zuplgg6kK22rZJEmiN0N5L/gxMN9vFYeLM4lZc8iLpnlEpt1VSWvZ+nFH4oo="
script:
  - bash gradlew build
  - bash gradlew sonarqube
branches:
  only:
    - master
